version: '3.9'

services:
  mongo_stwp:
    image: mongo_stwp
    restart: unless-stopped
    container_name: "mongo_stwp"
    ports:
        - "27017:27017"
    hostname: test-mongo # hostname is needed for replica set
    volumes:
        - ./data/db:/var/lib/mongodb
        - ./etc/mongo:/etc/mongo/
